"""Regenerate src/sign-images.js from the sign PNG in assets/.

Run after changing assets/speed_limit_sign.png (the distance sign is drawn as vector
shapes in track-generator.js, traced from assets/distance_sign.png):

    python3 embed_sign_images.py
"""
import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parent
IMAGES = ["assets/speed_limit_sign.png"]

lines = [
    "// Generated by embed_sign_images.py from assets/*.png - do not edit by hand.",
    "// The speed-limit sign image inlined as a data URI, so an exported SVG/PNG carries it even when",
    "// index.html is opened from disk (file://), where fetch() of a local asset is blocked.",
    "window.SIGN_IMAGES = {",
]
for name in IMAGES:
    data = base64.b64encode((ROOT / name).read_bytes()).decode("ascii")
    lines.append(f"    '{name}': 'data:image/png;base64,{data}',")
lines.append("};")
(ROOT / "src" / "sign-images.js").write_text("\n".join(lines) + "\n")
